### ISSUE TITLE
cpcode creation fails for "invalid.data"

### ISSUE THREAD

**Issue by dhardy92** [akamaimike/akamai-terraform-templates#1]
Hello,

We are traying to manage our Akamaï properties with terraform.
This repo seams very helpfull as we did not manage to do it for a couple of weeks.

We are testing Akamaï for now with a dummy domain name (=cpcode_name as best practice).
I think I set the rigth variables in `property.auto.tfvars`

```
[...]
  # akamai_cp_code.cp_code will be created
  + resource "akamai_cp_code" "cp_code" {
      + contract    = (known after apply)
      + contract_id = "ctr_V-3UJU4QJ"
      + group       = (known after apply)
      + group_id    = "grp_200933"
      + id          = (known after apply)
      + name        = "test.keljob.com"
      + product     = (known after apply)
      + product_id  = "prd_Fresca"
    }
[...]

akamai_cp_code.cp_code: Creating...
akamai_edge_hostname.edge_hostname: Creating...
akamai_edge_hostname.edge_hostname: Creation complete after 2s [id=ehn_4931421]

Error: creating CP Code: API error: 
{
	"type": "cpcode/create_error",
	"title": "CPCode create request failed",
	"detail": "CPCode creation failed, see errors for more details",
	"instance": "https://akab-okdkfma4q6ry6ylz-6easbyxxk4zkpkie.luna.akamaiapis.net/papi/v1/cpcodes?contractId=ctr_V-3UJU4QJ\u0026groupId=grp_200092#84e2610cf8ce6ac3",
	"statusCode": 422,
	"errors": [
		{
			"type": "about:blank",
			"title": "Creation of cpcode failed",
			"code": "invalid.data",
			"details": [
				{
					"code": "invalid.data",
					"message": "The services are invalid or are not part of the selected contracts",
					"data": {
						"cpcodeName": "cpcodetest.keljob.com"
					}
				}
			]
		}
	]
}

```

Do I need some pre creation of cpcode in my contract before applying ?

**Comment by akamaimike** [comment]
Hi dhardy92, thanks for reaching out and great you found these Akamai Terraform templates so quickly after upload. 

The issue you are getting is that you are trying to create an Akamai CP Code tied to product Akamai Ion (prd_Fresca). This product is probably not on your account. You might have Dynamic Site Accelerator, in that case the product ID would be prd_Site_Accel.  (This is error line; "The services are invalid or are not part of the selected contracts")

That said, this template is only compatible with Akamai Ion right now and not yet with Dynamic Site Accelerator. I still have to take the DSA template and add that in here as an option. 

If you were to use this template right now, you would load in the Ion template inside of a DSA configuration and get several issues at activation that you are trying to add Akamai Ion features unavailable in DSA. Hopefully that makes sense.

If you have any further questions on the Akamai Terraform Provider, feel free to hop over to our Akamai Slack, channel #akamai-terraform: https://akamai-serverless.slack.com/join/shared_invite/zt-8cfgauio-X5HmBIUXP4hr898gyUpnMA#/ Happy to answer further questions there.

/Mike

**Comment by akamaimike** [comment]
Hi dhardy92,

I just added a new template in the folder property-template-dsa. This should spin up a basic Akamai DSA configuration with a CP Code and Edge Hostname tied to DSA as well. 

I also changed the flag cert type to CPS_Managed so it will load your certificate created through the Certificate Provisioning System (you can also do this with Terraform but that is not in this template). See here: https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cps_dv_enrollment

It can be found here: https://github.com/akamaimike/akamai-terraform-templates/tree/main/property-template-akamai-dsa 

I was able to deploy a DSA config on two test accounts with this, so hopefully it works for you as well.

Good luck with Terraforming and if you have any questions, let me know on Slack. 

/Mike

**Comment by dhardy92** [comment]
Thank you for this.
